---
title: "Research"
---

***

- __Publications__

    * Gueye, Ghislain; Hyeongwoo Kim, and Gilad Sorek (Forthcoming), ["Pitfalls in Testing for Cointegration between Inequality and the Real Income,"](https://ideas.repec.org/p/abn/wpaper/auwp2016-07.html) Accepted, ***Economic Inquiry***.

***

- __Working papers__ *(Paper titles subject to change)*

    * Gueye, Ghislain, __*"Co-movements between House Prices and some Fundamentals: A study of OECD Countries"*__

***

- __School projects__

      * Gueye, Ghislain, __*"Are Trade and Migration Complementary or Substitutable? A Case Study of Côte d'Ivoire"*__ (International trade field course, Auburn University, Fall 2013)

      * Gueye, Ghislain, __*"An Empirical Investigation of the Impact of Education and Returns to Skill on Civic Engagement in Africa"*__ (Term paper, microeconometrics, Auburn University, Spring 2013)
    
      * Gueye, Ghislain, __*"Are Sons More Valued Than Daughters? An Empirical Study"*__ (Term paper, econometrics, Auburn University, Fall 2012)
      
      * Gueye, Ghislain, __*"Workers' Remittances and their Effect on the Economic Growth of Côte d'Ivoire"*__ (Term paper, graduate macroeconomics, Auburn University, Spring 2012)
      
      * Gueye, Ghislain, __*"The Extent of Ghana's Dependency on the Rest of the World"*__ (Undergraduate thesis, Central University College (Accra, Ghana), Summer 2010)

